//Error handling
let a = 10;
let b = 52;
console.log(a+b)
try{
    console.log(a+c);
} catch(err){
    console.log(err);
}
console.log(a+b)